:title: 'Boilerplate'

:routing:
  :home:
    :root: /
    :actions:
  :account:
    :root: /conta
    :actions:
      :new: /nova-conta
  :security:
    :root: /secao
    :actions:
      :login: /login
      :logout: /logout
